Pin mher/flower Docker image to fix startup error
tiangolo/full-stack-fastapi-postgresql#398
tiangolo/full-stack-fastapi-postgresql#399

Error:

```text
ERROR: for flower  Cannot start service flower: OCI runtime create
failed: container_linux.go:380: starting container process caused:
exec: "celery --broker=amqp://guest@queue:5672//":
stat celery --broker=amqp://guest@queue:5672//:
no such file or directory: unknown
```